jobs:
- template: azure-windows.yml
  parameters:
    name: windows_debug_x64
    pool: 'windows-latest'
    configuration: Debug

- template: azure-windows.yml
  parameters:
    name: windows_release_x64
    pool: 'windows-latest'
    configuration: Release

- template: azure-unix.yml
  parameters:
    name: ubuntu_debug_x64
    container: 'finitereality/novelrt-build:latest'
    configuration: Debug

- template: azure-unix.yml
  parameters:
    name: ubuntu_release_x64
    container: 'finitereality/novelrt-build:latest'
    configuration: Release
